server:
  port: 8188
  servlet:
    context-path: /shop-auth
spring:
  flyway:
    baseline-on-migrate: true
    #    url: jdbc:postgresql://localhost:5432/postgres/winter_shop
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path%3Dwinter_shop
    user: postgres
    password: 130592
    validate-on-migrate: false
  #    default-schema: winter_shop
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path%3Dwinter_users
    username: postgres
    password: 130592
  #    dbcp2:
  #      default-schema: winter_shop
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: true

jwt:
  secret: EI&!%Ti34NeSmOtRi7666SUDA23232eto43SEcRET@#$%^&%$@Ponyal?uroD
  lifetime: 36000000