server:
  port: 8189
  servlet:
    context-path: /shop
spring:
  flyway:
    baseline-on-migrate: true
#    url: jdbc:postgresql://localhost:5432/postgres/winter_shop
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path%3Dwinter_shop
    user: postgres
    password: 130592
    validate-on-migrate: false
#    default-schema: winter_shop
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path%3Dwinter_shop
    username: postgres
    password: 130592
#    dbcp2:
#      default-schema: winter_shop
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: true

#jwt:
#  secret: EI&!%Ti34NeSmOtRi7666SUDA23232eto43SEcRET@#$%^&%$@Ponyal?uroD
#  lifetime: 36000000


#server.port = 8189
#server.servlet.context-path = /shop
#
#spring.flyway.baseline-on-migrate = true
#spring.flyway.url = jdbc:postgresql://localhost:5432/postgres
#spring.flyway.user = postgres
#spring.flyway.password = 130592
#spring.flyway.validate-on-migrate = false
#
#spring.datasource.driver-class-name = org.postgresql.Driver
#spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username = postgres
#spring.datasource.password = 130592
#
#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.database = postgresql
#spring.jpa.open-in-view = true
#
#jwt.secret = EI&!%Ti34NeSmOtRi7666SUDA23232eto43SEcRET@#$%^&%$@Ponyal?uroD
#jwt.lifetime = 36000000
